@copy .pio\build\ttgo-t1-esp-idf\firmware.bin ".\Lilygo TTGO T1.bin"
@copy .pio\build\m5stack-core2-esp-idf\firmware.bin ".\M5 Stack Core2.bin"
@copy .pio\build\m5stack-fire-esp-idf\firmware.bin ".\M5 Stack Fire.bin"
@copy .pio\build\esp-wrover-kit-esp-idf\firmware.bin ".\Espressif ESP_WROVER_KIT 4.1.bin"
@copy .pio\build\ESP-Display-S3\firmware.bin ".\Makerfabs ESP Display S3 3.5 inch.bin"
@copy .pio\build\esp-display-4inch\firmware.bin ".\Makerfabs ESP Display S3 4 inch.bin"
@copy .pio\build\ESP-Display-4_3inch\firmware.bin ".\Makerfabs ESP Display S3 4.3 inch.bin"
@copy .pio\build\ESP-Display-7inch\firmware.bin ".\Makerfabs ESP Display S3 7 inch.bin"
@copy .pio\build\T-Display-S3\firmware.bin ".\Lilygo T-Display S3.bin"
@copy .pio\build\WaveShare-ESP32S3-4_3inch\firmware.bin ".\Waveshare ESP32S3 4.3 inch.bin"